apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c7tu9t36m-go
  janus-idp.io/tekton: c7tu9t36m-go
  backstage.io/kubernetes-id: c7tu9t36m-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c7tu9t36m-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
